version: "3.7"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
    - grafana-data:/var/lib/grafana
    ports:
    - 3001:3000
    networks:
      - monitoreo_apps

  alertmanager-container:
    image: ubuntu/alertmanager:0.25.0-22.04_stable
    container_name: alertmanager-container
    restart: unless-stopped
    ports:
    - 9093:9093
    environment:
      - TZ=UTC
    volumes:
    - ./alertmanager.yml:/alertmanager.yml
    command: --config.file=/alertmanager.yml --log.level=debug
    networks:
      - monitoreo_apps

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    restart: unless-stopped
    volumes:
    - ./loki-config.yml:/etc/loki/local-config.yaml
    command:
    - -config.file=/etc/loki/local-config.yaml
    ports:
    - 3100:3100
    networks:
      - monitoreo_apps

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-data:/prometheus
    ports:
    - 9090:9090
    environment:
      - DISCOURSE_PROMETHEUS_WEBSERVER_BIND='*'
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention.time=1y'
    - '--web.enable-lifecycle'
    networks:
      - monitoreo_apps

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
    - 9100:9100
    command:
    - '--path.rootfs=/host'
    pid: host
    volumes:
    - '/:/host:ro,rslave'
    networks:
      - monitoreo_apps

  nexus_exporter:
    image: ocadotechnology/nexus-exporter:latest
    container_name: nexus_exporter
    restart: unless-stopped
    ports:
    - 9184:9184
    env_file:
      - 'env.nexus_exporter'
    networks:
      - monitoreo_apps

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
    - 8880:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoreo_apps

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    privileged: true
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - 9115:9115
    networks:
      - monitoreo_apps

  telegraf:
    image: telegraf:latest
          #    image: telegraf:1.16.3
    container_name: telegraf
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'
    networks:
      - monitoreo_apps
      - monitoreo_default
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf

  influxdb:
    image: influxdb:1.8.10
          #image: influxdb:1.8.3
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - 'env.influxdb'
    volumes:
      - ./data_influxdb:/var/lib/influxdb
    networks:
      - monitoreo_apps
      - monitoreo_default

volumes:
  grafana-data:
  prometheus-data:

networks:
  monitoreo_apps:
  monitoreo_default:
    external: true
