global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    metrics_path: /metrics
    static_configs:
    - targets: ['node_exporter:9100']

  - job_name: 'jenkins'
    metrics_path: /prometheus/
    static_configs:
     - targets: ['jenkins:8080']

  - job_name: 'nexus3'
    metrics_path: /
    static_configs:
     - targets: ['nexus_exporter:9184']

  - job_name: 'influxdb'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
     - targets: ['influxdb:8086']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
     module: [http_2xx]
    static_configs:
     - targets: ['www.justwatch.com', 'www.hispasat.com']

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.
